### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HoodedMenace9** [devz3ro/Arc-Windows-10#1]
![Ukc1sQDEw6](https://github.com/devz3ro/Arc-Windows-10/assets/113478626/0a35ee4a-19ca-49a7-9e94-07ca5fe41297)

**Comment by devz3ro** [comment]
Open a PowerShell window and change directory to where you downloaded and ran the arcwin10.bat file. Execute the following command and post the output:

`Select-String -Path "Arc/AppxManifest.xml" -Pattern "Windows.Desktop"`

**Comment by devz3ro** [comment]
Try with the new 1.1 files, it doesn't extract the msix, and installs directly.

**Comment by devz3ro** [comment]
Added more checks to 1.2, try with this version and let me know if you have any other issues.

**Comment by HoodedMenace9** [comment]
that worked. thanks! Does import from old browser not work?

**Comment by HoodedMenace9** [comment]
nvm I dont think it supports importing from Thorium
