### ISSUE TITLE
still not install dependencies

### ISSUE THREAD

**Issue by pp03** [devz3ro/Arc-Windows-10#10]
version 1.2.1 is still not extracting vclibs on clean install windows. there is an error that installed version of vclibs is 14.0.27629.0 and required version is 14.0.30704.0

**Comment by devz3ro** [comment]
please paste screenshots or text of the error

**Comment by pp03** [comment]
Windows cannot install package because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.30704.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x64__8wekyb3d8bbwe

**Comment by devz3ro** [comment]
Try running this from a (Administrator) PowerShell:

`get-appxpackage Microsoft.VCLibs.140.00 -allusers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`

**Comment by pp03** [comment]
unfortunately still the same

**Comment by devz3ro** [comment]
Hard to debug this because of the many things that depend on the vclibs (can't remove to test).

See if installing the x64 of the vc_redist works.

[https://aka.ms/vs/17/release/vc_redist.x64.exe](url)
[https://aka.ms/vs/17/release/vc_redist.x86.exe](url)

Do you have the microsoft store installed? That also relies on the vclibs I believe.

**Comment by pp03** [comment]
unfortunately x64 and x86 of the vc_redist doesn't work.
yes, store is installed.

there is vc_redist link in appinstaller file - i'll try that

**Comment by pp03** [comment]
manual installation of vc_redist from appinstaller file works.

is there any chance to integrate that with your script?

**Comment by devz3ro** [comment]
I think I added / fixed it correctly, please download the 1.2.2 release and try it. Let me know if you run into any issues.

**Comment by pp03** [comment]
it's working. 

there is no need to download and install the latest Windows App SDK

**Comment by pp03** [comment]
can you change script by ignoring segoe font if it is installed?

**Comment by devz3ro** [comment]
added the font check routine in 1.2.4.
