### ISSUE TITLE
Arc Browser  doesn't open after signing in

### ISSUE THREAD

**Issue by seizue** [devz3ro/Arc-Windows-10#13]
Arc Browser doesn't open after signing in. I have  to  Terminate, Reset and Repair just to make the browser appear again. the problem is its back asking for sign in. which is the problem. After signing in then closing the arc browser. It wont open again

![Screenshot 2024-05-11 235402](https://github.com/devz3ro/Arc-Windows-10/assets/25120376/7d44febb-3f7a-4d86-bacc-565dd1100978)

**Comment by devz3ro** [comment]
Unfortunately this is an issue with the app itself, not the installer.
