### ISSUE TITLE
how do I open Arc after install?

### ISSUE THREAD

**Issue by cartoonie** [devz3ro/Arc-Windows-10#15]
![image](https://github.com/devz3ro/Arc-Windows-10/assets/67033080/34a26354-ec34-4cca-922b-805d886bbef9)

I've downloaded everything needed (I think), but where do I open arc, I cant find it anywhere

**Comment by cartoonie** [comment]
Arc.appinstaller downloaded.
Microsoft.WindowsAppRuntime.1.5 is up to date. Installed version: 5001.119.156.0. Required version from XML: 5001.119.156.0                                                                                                                     Microsoft.VCLibs.140.00.UWPDesktop has a higher version installed than required. Installed version: 14.0.33519.0. Required version from XML: 14.0.30704.0                                                                                       Segoe Fluent Icons zip downloaded.                                                                                      Segoe Fluent Icons zip extracted.                                                                                       New-ItemProperty : Requested registry access is not allowed.                                                            At C:\Users\me\OneDrive\Desktop\arch\arcwin10-1.2.2.ps1:85 char:5                                                         New-ItemProperty -Path $regPath -Name "$fontNameWithoutExtension  ...                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                      CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...ntVersion\Fonts:String) [New-ItemProperty], Securit     yException                                                                                                                FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.NewItemPropertyCommand                                                                                                                            Segoe Fluent Icons.ttf installed.                                                                                       Setting UBR to new value. Original UBR: 4291 (Decimal), 10c3 (Hex), Type: Int32                                         Set-ItemProperty : Requested registry access is not allowed.                                                            At C:\Users\me\OneDrive\Desktop\arch\arcwin10-1.2.2.ps1:57 char:5                                                         Set-ItemProperty -Path $path -Name $name -Value $decimalValue -Ty ...                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                      CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...\CurrentVersion:String) [Set-ItemProperty], Securit     yException                                                                                                               + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand                                                                                                                            Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.     Windows cannot install package TheBrowserCompany.Arc_1.1.1.27314_x64__ttt1ap7aakyb4 because this package is not         compatible with the device. The package requires OS version 10.0.22000.0 or higher on the Windows.Desktop device        family. The device is currently running OS version 10.0.19045.4291.                                                     NOTE: For additional information, look for [ActivityId] 441fa3ae-a3a9-0002-c262-2244a9a3da01 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 441fa3ae-a3a9-0002-c262-2244a9a3da01
At C:\Users\em\OneDrive\Desktop\arch\arcwin10-1.2.2.ps1:35 char:9
        Add-AppxPackage -Path $PackagePath
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (C:\Users\me\...mp\Arc.x64.msix:String) [Add-AppxPackage], Exception
     FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Package installed: TheBrowserCompany.Arc
Setting UBR to new value. Original UBR: 4291 (Decimal), 10c3 (Hex), Type: Int32
Set-ItemProperty : Requested registry access is not allowed.
At C:\Users\me\OneDrive\Desktop\arch\arcwin10-1.2.2.ps1:57 char:5
     Set-ItemProperty -Path $path -Name $name -Value $decimalValue -Ty ...
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...\CurrentVersion:String) [Set-ItemProperty], Securit
   yException
     FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand

10c3
Int32
UBR restored to original value: 10c3, Type: Int32
Cleanup completed. All temporary files removed.
Press Enter to exit ...

**Comment by devz3ro** [comment]
Did you right click and run the .bat file as Administrator?

"Requested registry access is not allowed." is in your log output.

**Comment by cartoonie** [comment]
> Did you right click and run the .bat file as Administrator?
> 
> "Requested registry access is not allowed." is in your log output.

that worked perfectly, thank you very much!

**Comment by cartoonie** [comment]
![image](https://github.com/devz3ro/Arc-Windows-10/assets/67033080/a534c114-43f0-4773-bc91-152a1d23abcb)
