### ISSUE TITLE
Request: log Arc appxpackage versions on successful upgrade

### ISSUE THREAD

**Issue by pem884** [devz3ro/Arc-Windows-10#18]
Think this already happens when necessary, so I suppose I'm proposing something that would normally be more of a debug feature. Be that as it may, I like to see in the log what version I came from and upgraded to (call it a leftover from an appxpackage I used to work with where we had dependency issues)

I suggest we could take the - I think it's `mainPackage.Version` - and simply output it to logs as we inspect it. Or any similar version of that; I'm not picky about it.

I'd be happy to submit a PR if I beat you to it; I should probably not do this right now though :)

# Example, content of `Arc.appinstaller(05-21-2024-0329PM).log`:
```log
Arc.appinstaller downloaded.
Microsoft.WindowsAppRuntime.1.5 is up to date. Installed version: 5001.119.156.0. Required version from XML: 5001.119.156.0
Microsoft.VCLibs.140.00.UWPDesktop has a higher version installed than required. Installed version: 14.0.33519.0. Required version from XML: 14.0.30704.0
Segoe Fluent Icons.ttf is already installed. Skipping installation.
Setting UBR to new value. Original UBR: 4412 (Decimal), 113c (Hex), Type: Int32
Package installed: TheBrowserCompany.Arc
Setting UBR to new value. Original UBR: 4294967295 (Decimal), ffffffff (Hex), Type: UInt32
UBR restored to original value: 113c, Type: Int32
Cleanup completed. All temporary files removed.
```

# Proposed:
**_Package found: TheBrowserCompany.Arc vA.BCD_**
Package installed: TheBrowserCompany.Arc **_vW.XYZ_**

**Comment by devz3ro** [comment]
I already have that coded for the dependencies, just need to add it to the main package.

I'll add it when I get the chance to add the code to close the arc.exe process to upgrade arc (vs closing manually).
