### ISSUE TITLE
deployment failed

### ISSUE THREAD

**Issue by pp03** [devz3ro/Arc-Windows-10#2]
win 10 clean install and error: windows cant install arc because this package depends on vclibs140

**Comment by devz3ro** [comment]
Will update the script to check for the dependencies when I get a chance. Most systems already have them installed, but on a clean windows 10 install I can see why they wouldn't be. They are actually provided in the Arc.appinstaller file, I just need to parse them out, check if they are installed and install if not.

Dependencies:
Microsoft.WindowsAppRuntime.1.5
Microsoft.VCLibs.140.00.UWPDesktop

Stay Tuned.

**Comment by devz3ro** [comment]
Try with version 1.2, I added the logic to install these dependencies if they don't exist.
