### ISSUE TITLE
Where are Arc files stored if I installed Arc using the arcwin10-1.2.4.1.bat file?

### ISSUE THREAD

**Issue by CrocodileDuty** [devz3ro/Arc-Windows-10#20]
Arc.appinstaller downloaded.
Microsoft.WindowsAppRuntime.1.5 has a higher version installed than required. Installed version: 5001.178.1908.0. Required version from XML: 5001.119.156.0
Microsoft.VCLibs.140.00.UWPDesktop is up to date. Installed version: 14.0.33728.0. Required version from XML: 14.0.33728.0
Segoe Fluent Icons.ttf is not installed. Proceeding with download and installation.
Segoe Fluent Icons zip downloaded.
Segoe Fluent Icons zip extracted.
Segoe Fluent Icons.ttf installed.
Setting UBR to new value. Original UBR: 4651 (Decimal), 122b (Hex), Type: Int32
Package installed: TheBrowserCompany.Arc
Setting UBR to new value. Original UBR: 4294967295 (Decimal), ffffffff (Hex), Type: UInt32
UBR restored to original value: 122b, Type: Int32
Cleanup completed. All temporary files removed.

------

I can run Arc after searching for it in the Cortona search but I don't know where its file are located in my disk.

**Comment by devz3ro** [comment]
C:\Program Files\WindowsApps\TheBrowserCompany

**Comment by CrocodileDuty** [comment]
![image](https://github.com/user-attachments/assets/d622ddc1-32d2-420e-8f39-71b7d62cd350)
![image](https://github.com/user-attachments/assets/4a9e0181-0f78-4ac0-9ecd-3f20ecf682a6)
![image](https://github.com/user-attachments/assets/52ca897e-4d2c-4ea9-a730-02dd4b0216dc)

**Comment by devz3ro** [comment]
It's there, "WindowsApps" is a hidden folder. It's hidden on purpose because you generally should not be messing with windows store apps.

**Comment by CrocodileDuty** [comment]
> It's there, "WindowsApps" is a hidden folder. It's hidden on purpose because you generally should not be messing with windows store apps.

Dumb me! Just installed Windows 10 again on my desktop and forgot this basic thing ;-; Thankyou for the help!
