### ISSUE TITLE
Nothing happen

### ISSUE THREAD

**Issue by iqsalah** [devz3ro/Arc-Windows-10#3]
I run the script with administrator permission but nothing happen? how to fix it ?

**Comment by devz3ro** [comment]
You will have to post screenshots or give more of a description. Are you downloading both ps1 and bat file to a common directory and running only the bat file as administrator?

**Comment by owyongsk** [comment]
I had a similar issue, try and see if you can launch cmd.exe from Window's start menu. If nothing shows up. Follow the instructions [here](https://stackoverflow.com/questions/68487328/command-prompt-not-opening-in-windows-10). Try running cmd.exe again, if it works. You can follow origin instruction in the readme for this installer.

**Comment by midpoint** [comment]
Arc.appinstaller downloaded.
Package Microsoft.WindowsAppRuntime.1.5 v5001.70.1338.0 is already installed with version v5001.119.156.0.
Package Microsoft.VCLibs.140.00.UWPDesktop v14.0.30704.0 is already installed with version v14.0.30704.0.
Segoe Fluent Icons zip downloaded.
Segoe Fluent Icons zip extracted.
Segoe Fluent Icons.ttf installed.
Setting UBR to new value. Original UBR: 4294967295 (Decimal), ffffffff (Hex), Type: UInt32
Package installed: TheBrowserCompany.Arc
Setting UBR to new value. Original UBR: 4294967295 (Decimal), ffffffff (Hex), Type: UInt32
UBR restored to original value: ffffffff, Type: UInt32
Cleanup completed. All temporary files removed.

安装完，运行arc没有任何反应。
After installation, running arc doesn't do anything.

**Comment by devz3ro** [comment]
> Arc.appinstaller downloaded. Package Microsoft.WindowsAppRuntime.1.5 v5001.70.1338.0 is already installed with version v5001.119.156.0. Package Microsoft.VCLibs.140.00.UWPDesktop v14.0.30704.0 is already installed with version v14.0.30704.0. Segoe Fluent Icons zip downloaded. Segoe Fluent Icons zip extracted. Segoe Fluent Icons.ttf installed. Setting UBR to new value. Original UBR: 4294967295 (Decimal), ffffffff (Hex), Type: UInt32 Package installed: TheBrowserCompany.Arc Setting UBR to new value. Original UBR: 4294967295 (Decimal), ffffffff (Hex), Type: UInt32 UBR restored to original value: ffffffff, Type: UInt32 Cleanup completed. All temporary files removed.
> 
> 安装完，运行arc没有任何反应。 After installation, running arc doesn't do anything.

Looks like you tried to do this manually before?

This line (the first occurrence) in the log you attached shows that your original UBR value is already set to "ffffffff": `Setting UBR to new value. Original UBR: 4294967295 (Decimal), ffffffff (Hex), Type: UInt32`

If you haven't set it manually, how many times have you ran the PowerShell script? Have you stopped it in the middle of execution or executed it multiple times before waiting for it to finish?

Either way, if you have multiple log files, look through them and see if you can find one that has something other than "ffffffff" and paste it here. You can either set it back manually or I can write a quick script to set it back for you.

**Comment by mbouksim** [comment]
@devz3ro I have the same error `Setting UBR to new value. Original UBR: 4294967295 (Decimal), ffffffff (Hex), Type: UInt32` change it back to **10c3** (found the values in an older log file) now it is tuck at  `Setting UBR to new value. Original UBR: 68633 (Decimal), 10c19 (Hex), Type: Int32`
Thank you
