### ISSUE TITLE
Reset UBR value 

### ISSUE THREAD

**Issue by eternity4318** [devz3ro/Arc-Windows-10#4]
I'm having issues updating Windows. I think it may have to do with the modified UBR value. How would I reset it to the correct value?

**Comment by devz3ro** [comment]
the UBR value is reset back to the original value after successful installation. The original UBR value is saved in the log file that is created in the same directory as the powershell script.

Open Registry Editor (regedit)
Navigate to: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
UBR

I will test again to make sure it's properly setting the value back and fix if required.

**Comment by menachem1** [comment]
Got it, thanks.

**Comment by eternity4318** [comment]
Got it, thanks.

**Comment by devz3ro** [comment]
Did you try to change this value manually? Can you paste me the output of the log file so I can see why it didn't set the original value back? I just tried it myself by uninstalling Arc and it properly changed the value to and back.

**Comment by eternity4318** [comment]
No,
I already deleted the log file,
It's possible that it was changed correctly and there's another issue blocking my update.
