### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by MahdiAkrami01** [devz3ro/Arc-Windows-10#5]
the arc installed successfully but after open it it is not working
no matter what url i typing the result is black

![image](https://github.com/devz3ro/Arc-Windows-10/assets/54323929/8c3f6d6c-f65d-496f-9db4-081d71279f08)

**Comment by pp03** [comment]
uninstall, install again and DO NOT turn off graphic acceleration

**Comment by cdnutter** [comment]
I appear to have this problem over RDP as there is no graphic acceleration unfortunately.
I'm sure there's nothing that can be done to fix until TBC fixes it. (or is it even an issue over W11 RDP?)

**Comment by sxlievo** [comment]
I got the same issue, i tried reinstalling

**Comment by MahdiAkrami01** [comment]
> turn off graphic acceleration

thanks for reply. where is graphic acceleration option ? how to ensure that this option is enabled ?

**Comment by devz3ro** [comment]
In the address bar go here: **arc://settings/system**

Make sure the following is enabled "Use graphics acceleration when available"

![image](https://github.com/devz3ro/Arc-Windows-10/assets/6265569/860e585b-fe1a-4424-be5f-2bb1623acfe5)

**Comment by MahdiAkrami01** [comment]
> In the address bar go here: **arc://settings/system**
> 
> Make sure the following is enabled "Use graphics acceleration when available"
> 
> ![image](https://private-user-images.githubusercontent.com/6265569/328370304-860e585b-fe1a-4424-be5f-2bb1623acfe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjg1MDUsIm5iZiI6MTcxNTA2ODIwNSwicGF0aCI6Ii82MjY1NTY5LzMyODM3MDMwNC04NjBlNTg1Yi1mZTFhLTQ0MjQtYmU1Zi0yYmIxNjIzYWNmZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDc1MDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjk3N2UxODIxOGI5Y2M1ZWQwM2Y3YjBmOWJiZDczZTRlZWFjMzkyY2E2MGJjNzQ5MGU5MzNhOGM3NTNiYWJjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4vRQ1P3xpRl36BP2kQc5MlGhyNtWmOR4CxCN7skk0NA)

everything is black!
![image](https://github.com/devz3ro/Arc-Windows-10/assets/54323929/291b69e9-20b0-4151-b29e-3f1fa1b61b0b)

**Comment by EduardoStarZ** [comment]
Have this same problem

So, it appears that Arc actually defaults graphics acceleration to off for some people

While this bug happens, the document of sites doesn't load visually, although the elements do appear (you can see it by hovering mouse on some elements with hover effects), but any interaction with this elements are not processed.

I did tried to turn on graphics acceleration while following in the dark on the system settings, it did not worked.

The only thing that seemed to work was the "Open proxy configurations" link, that did opened windows proxy options.

If there is any way of changing chromium settings through system files, this issue will be relatively easy to fix if that's the only problem

**Comment by devz3ro** [comment]
Unfortunately this is an issue with the app itself, not the installer.
