### ISSUE TITLE
.BAT exection fails with syntax error

### ISSUE THREAD

**Issue by bobseery** [devz3ro/Arc-Windows-10#6]
When arcwin10-1.2.1.bat is executed as admin on my win10 machine, it produces a syntax error:

The syntax of the command is incorrect.
<!DOCTYPE html>

This was running it from a CMD window.  If I Run As Admin, it closes the window too quickly to read.

Also, the readme.md file contains another version of the .bat file--not directions.

**Comment by bobseery** [comment]
I also tried it with a CMD window that I ran as Admin and it failed the same way.

**Comment by devz3ro** [comment]
Fixed the readme for the 1.2.1 version, please post screenshots or copy and paste the syntax error text you are receiving.

**Comment by bobseery** [comment]
![arc install](https://github.com/devz3ro/Arc-Windows-10/assets/168737559/ddf7b1f5-a994-4721-8f7e-eb3fbbff0de7)

**Comment by devz3ro** [comment]
please try with typing out the full file name: "arcwin10-1.2.1.bat"

**Comment by bobseery** [comment]
![arc install 2](https://github.com/devz3ro/Arc-Windows-10/assets/168737559/3f6e20c8-f4a9-4a5a-9a06-9ebe9922df63)
I tried that before with the same result.

**Comment by devz3ro** [comment]
How did you download the bat and ps1 files? The sizes look off.

This is how it should look, it looks like you downloaded the web page and not the raw file.

![image](https://github.com/devz3ro/Arc-Windows-10/assets/6265569/c3da1a85-b3bf-4138-ae3a-dbaf27339941)

Delete the files you have and go here and download, then right click the bat file + run as admin should work for you:

https://github.com/devz3ro/Arc-Windows-10/releases/tag/ArcWindows10Installer-1.2.1

**Comment by Cosmic-Wolf** [comment]
As @devz3ro points out, you should download files from the release page. Also, I'd like to inform that, for some reason, the execution fails, if I run the files from Desktop or from Documents.

**Comment by bobseery** [comment]
That was the problem.  I have it installed and working.  Thanks for your help and sorry for being such a newb!
