### ISSUE TITLE
Symbol not showing correctly

### ISSUE THREAD

**Issue by mzmonkey** [devz3ro/Arc-Windows-10#7]
Pretty much all Symbols appear as ▯ or something similar (See Picture).
Already tried doing a fresh install twice, always end up with these symbols not loading.
![image](https://github.com/devz3ro/Arc-Windows-10/assets/75185931/cbe3b693-b333-4ed5-9d26-07f1066e32bd)

**Comment by devz3ro** [comment]
Please post the output of the log file.
