### ISSUE TITLE
Fails to change the reg value

### ISSUE THREAD

**Issue by Novikomp** [devz3ro/Arc-Windows-10#9]
It starts in an elevated prompt but still fails to change the required reg value (see screenshot).
I was able to install it manually since the procedure is simple but thought to report it someone else might have the same problem.
Cheers!
![Fail](https://github.com/devz3ro/Arc-Windows-10/assets/153067667/f141afc0-8bac-4aa4-99f1-6e22cbc12ca4)

**Comment by ZallP** [comment]
![Screenshot (1)](https://github.com/devz3ro/Arc-Windows-10/assets/87319970/cffe2758-e0f7-454e-8134-08fceb2daa9c)
![Screenshot (3)](https://github.com/devz3ro/Arc-Windows-10/assets/87319970/78c0d10a-41a1-488d-8fd0-9bee5fab2a36)
Just turn off your real time protection and other antivirus, i have the same problem but after i do that its fixed and finnaly worked
